/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    places: Place;
    tags: Tag;
    articles: Article;
    destinations: Destination;
    pages: Page;
    experiences: Experience;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Ej: © Hotel Fasano Punta del Este
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  slug: string;
  type: 'dormir' | 'comer' | 'spots';
  destination?: (number | null) | Destination;
  featured?: boolean | null;
  tags?: (number | Tag)[] | null;
  heroImage?: (number | null) | Media;
  /**
   * Imagen para cards y listados. Si está vacío se usa la hero image.
   */
  cardImage?: (number | null) | Media;
  /**
   * Frase corta para cards y listados.
   */
  summary?: string | null;
  /**
   * Descripción de la ubicación del lugar.
   */
  location?: string | null;
  /**
   * Descripción completa para la página del lugar.
   */
  description?: string | null;
  gallery?:
    | {
        layout: 'duo' | 'grid' | 'featured-bottom' | 'featured-side';
        images: {
          image: number | Media;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Para hoteles: "Por qué alojarse aquí". Para restaurantes: "Tené en cuenta".
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    /**
     * URL de reserva (Booking, etc.). Si está vacío no se muestra el botón.
     */
    url?: string | null;
    /**
     * URL de Google Maps. Si está vacío no se muestra el link.
     */
    mapsUrl?: string | null;
  };
  /**
   * Grupos de lugares relacionados con título editorial.
   */
  relatedPlaces?:
    | {
        /**
         * Ej: "Para quedarse cerca", "Para comer después".
         */
        title: string;
        places: (
          | {
              relationTo: 'places';
              value: number | Place;
            }
          | {
              relationTo: 'experiences';
              value: number | Experience;
            }
        )[];
        id?: string | null;
      }[]
    | null;
  relatedArticles?: (number | Article)[] | null;
  /**
   * Si está vacío se usa el nombre del lugar.
   */
  seoTitle?: string | null;
  /**
   * Si está vacío se usa el summary.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Frase breve que define el destino. Ej: "Entre la arena y el campo"
   */
  tagline?: string | null;
  /**
   * Frase corta para cards y listados.
   */
  summary?: string | null;
  /**
   * Descripción completa del destino.
   */
  description?: string | null;
  /**
   * Si está vacío se usa el nombre del destino.
   */
  seoTitle?: string | null;
  /**
   * Si está vacío se usa el summary.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  label: string;
  type: 'dormir' | 'comer';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  slug: string;
  destination?: (number | null) | Destination;
  /**
   * Menor = primero.
   */
  order?: number | null;
  /**
   * Sección "Para empezar".
   */
  featured?: boolean | null;
  published?: boolean | null;
  heroImage?: (number | null) | Media;
  /**
   * Frase corta para cards y listados.
   */
  summary?: string | null;
  /**
   * Frase corta destacada, tipo subtítulo.
   */
  tagline?: string | null;
  content?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            variant?: ('inline' | 'breakout' | 'bleed') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            /**
             * El texto de la cita.
             */
            text: string;
            /**
             * Autor o fuente (opcional).
             */
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            place:
              | {
                  relationTo: 'places';
                  value: number | Place;
                }
              | {
                  relationTo: 'experiences';
                  value: number | Experience;
                }
              | {
                  relationTo: 'destinations';
                  value: number | Destination;
                };
            /**
             * Línea de contexto. Ej: "Para quedarse cerca" o "Ideal para almorzar después".
             */
            context?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'placeBlock';
          }
      )[]
    | null;
  /**
   * Puntos destacados de la experiencia.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Título de la sección (ej: "Cuándo ir", "Mejor momento").
   */
  timingTitle?: string | null;
  /**
   * Momentos del día con una descripción corta.
   */
  timing?:
    | {
        /**
         * Ej: Mañana, Tarde, Atardecer
         */
        moment: string;
        /**
         * Ej: Más tranquila, buen momento para caminar
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        layout: 'single' | 'duo';
        images: {
          image: number | Media;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Places y experiencias relacionadas.
   */
  related?:
    | (
        | {
            relationTo: 'places';
            value: number | Place;
          }
        | {
            relationTo: 'experiences';
            value: number | Experience;
          }
      )[]
    | null;
  /**
   * Si está vacío se usa el título.
   */
  seoTitle?: string | null;
  /**
   * Si está vacío se usa el summary.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  type: 'guide' | 'selection' | 'experience' | 'season';
  destinations?: (number | Destination)[] | null;
  /**
   * Menor = primero.
   */
  order?: number | null;
  /**
   * Home.
   */
  featured?: boolean | null;
  published?: boolean | null;
  heroImage?: (number | null) | Media;
  /**
   * Frase corta para cards y listados.
   */
  tagline?: string | null;
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            variant?: ('inline' | 'breakout' | 'bleed') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            /**
             * El texto de la cita.
             */
            text: string;
            /**
             * Autor o fuente (opcional).
             */
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            place:
              | {
                  relationTo: 'places';
                  value: number | Place;
                }
              | {
                  relationTo: 'experiences';
                  value: number | Experience;
                }
              | {
                  relationTo: 'destinations';
                  value: number | Destination;
                };
            /**
             * Línea de contexto. Ej: "Para quedarse cerca" o "Ideal para almorzar después".
             */
            context?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'placeBlock';
          }
        | {
            /**
             * Título opcional. Ej: "5 cosas que saber antes de ir".
             */
            title?: string | null;
            slides: {
              image: number | Media;
              /**
               * Frase corta, máximo 80 caracteres.
               */
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'socialCarousel';
          }
        | {
            source: 'embed' | 'upload';
            /**
             * URL del video de TikTok, Instagram Reel o YouTube Shorts.
             */
            embedUrl?: string | null;
            videoFile?: (number | null) | Media;
            /**
             * Texto debajo del video (opcional).
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'socialVideo';
          }
        | {
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'socialGallery';
          }
      )[]
    | null;
  /**
   * Places y experiencias relacionadas.
   */
  related?:
    | (
        | {
            relationTo: 'places';
            value: number | Place;
          }
        | {
            relationTo: 'experiences';
            value: number | Experience;
          }
      )[]
    | null;
  /**
   * Otros artículos relacionados.
   */
  relatedArticles?: (number | Article)[] | null;
  /**
   * Si está vacío se usa el título del artículo.
   */
  seoTitle?: string | null;
  /**
   * Si está vacío se usa el tagline.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  destination?: T;
  featured?: T;
  tags?: T;
  heroImage?: T;
  cardImage?: T;
  summary?: T;
  location?: T;
  description?: T;
  gallery?:
    | T
    | {
        layout?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        url?: T;
        mapsUrl?: T;
      };
  relatedPlaces?:
    | T
    | {
        title?: T;
        places?: T;
        id?: T;
      };
  relatedArticles?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  destinations?: T;
  order?: T;
  featured?: T;
  published?: T;
  heroImage?: T;
  tagline?: T;
  layout?:
    | T
    | {
        textBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        placeBlock?:
          | T
          | {
              place?: T;
              context?: T;
              id?: T;
              blockName?: T;
            };
        socialCarousel?:
          | T
          | {
              title?: T;
              slides?:
                | T
                | {
                    image?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        socialVideo?:
          | T
          | {
              source?: T;
              embedUrl?: T;
              videoFile?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        socialGallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  related?: T;
  relatedArticles?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  tagline?: T;
  summary?: T;
  description?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  destination?: T;
  order?: T;
  featured?: T;
  published?: T;
  heroImage?: T;
  summary?: T;
  tagline?: T;
  content?:
    | T
    | {
        textBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        placeBlock?:
          | T
          | {
              place?: T;
              context?: T;
              id?: T;
              blockName?: T;
            };
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  timingTitle?: T;
  timing?:
    | T
    | {
        moment?: T;
        description?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        layout?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  related?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}